version: '3'
services:


  spring:
    depends_on:
      - mysql
    image: eyabenamor/firstimage
    ports:
      - "8080:8080"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    restart: unless-stopped
