version: '3'
services:

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=kaddem
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER= root
      - MYSQL_PASS= root
    volumes:
      - /home/vagrant/mysql:/var/lib/mysql
    networks:
      - mynet



  mysql-exporter:
    container_name: mysql-exporter
    image: prom/mysqld-exporter:latest
    ports:
      - "9104:9104"
    volumes:
      - /home/vagrant/mysql-exporter/.my.cnf:/root/.my.cnf
    environment:
      - DATA_SOURCE_NAME='root:root@(mysql:3306)/db'
      - collect.info_schema.tablestats=true
      - collect.info_schema.userstats=true
      - collect.info_schema.query_response_time=true
      - collect.auto_increment.columns=true
      - collect.binlog_size=true
      - collect.perf_schema.eventsstatements=true
      - collect.perf_schema.eventswaits=true
      - collect.perf_schema.file_events=true
      - collect.perf_schema.indexiowaits=true
      - collect.perf_schema.tableiowaits=true
      - collect.perf_schema.tablelocks=true
    depends_on:
      - mysql
    networks:
      - mynet









  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8085:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - mynet




  newspring:
    container_name: newspring
    image: eyabenamor/newspring:latest
    restart: on-failure
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/kaddem?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
    networks:
      - mynet

  angular:
    container_name: angular_container
    image: eyabenamor/angular:latest
    ports:
      - "4200:80"
    depends_on:
      - newspring
    networks:
      - mynet

networks:
  mynet:

volumes:
  mysql:
