version: '3'
services:


  mysql-exporter:
    container_name: mysql-exporter
    image: prom/mysqld-exporter:latest
    ports:
      - "9104:9104"
    environment:
      - DATA_SOURCE_NAME=eya:new@(172.16.1.98:3306)/
    depends_on:
      - mysql
    networks:
      - mynet



  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=kaddem
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER= eya
      - MYSQL_PASS= new
    networks:
      - mynet




  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8085:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - mynet




  newspring:
    container_name: newspring
    image: eyabenamor/newspring:latest
    restart: on-failure
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/kaddem?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
    networks:
      - mynet

  angular:
    container_name: angular_container
    image: eyabenamor/angular:latest
    ports:
      - "4200:80"
    depends_on:
      - newspring
    networks:
      - mynet

networks:
  mynet:
