version: '3'
services:



  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=kaddem
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - mynet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - mynet




  spring:
    container_name: spring
    image: eyabenamor/newspring:latest
    restart: on-failure
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/kaddem?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
    networks:
      - mynet

  angular:
    container_name: angular_container
    image: eyabenamor/angular:latest
    ports:
      - "4200:80"
    depends_on:
      - newspring
    networks:
      - mynet

networks:
  mynet:
